name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, World!
    - name: Run a multi-line script 
      run: 
        echo Add other actions to the build job
        echo This can be unit test, etc.
        
